### PR TITLE
Added option "disableDays"

### PR DESCRIPTION
**Pull request by remigarcia**
Hello,

I needed to disable only Sundays, so the option "disableWeekends" didn't work for me.
I added an option to disable the week days you need.

### CODE REVIEW

**Comment by joericlaes** [comment]
I also needed this functionality, thanks for adding it! Hope this gets merged soon.

**Comment by ninetyninew** [comment]
Thank you for this it is exactly what we were looking for. We did attempt to do this ourselves by setting the is-locked class onRenderDay but while this locked the day from selection a user could still include it in a range of dates.

**Comment by ninetyninew** [comment]
I've just been using this on while it will show the dates as locked unfortunately you can select a range included these locked dates even when disallowLockDaysInRange is true. It looks the same for the disableWeekends option too, so i am going to raise a bug on that.

**Comment by tblanchard** [comment]
I need this too.

**Comment by wakirin** [comment]
See #157 
Updated `lockDays` option.

Example for weekends:
```
...
lockDays: (day) => {
   const d = day.getDay();

   return [6, 0].includes(d);
},
...
```

and with `disallowLockDaysInRange` option enabled:
```
...
lockDays: (date1, date2, pickedDates) => {
        const d1 = date1.clone();
        const d2 = date2.clone();

        while (d1.getDateInstance() < d2.getDateInstance()) {
          const day = d1.getDay();
          isWeekend = [6, 0].includes(day);
          if (isWeekend) { return true; }
          d1.add(1, 'day');
        }

        return false;
},
...
```

v2 is currently in beta and is available on npm.
`npm i litepicker@2.0.0-beta.0`

**Pull request closed without merging**
