### PR TITLE
Feature/Reset button #46

### PR DESCRIPTION
**Pull request by EmilienLeroy**
## Description
Close issue #46 

I have added two options :
* useResetBtn
* resetBtnCallback

By default the reset button will clear the current selection.

## Exemple
clearBtn

## How to use
```JS
var picker = new Litepicker({ 
    element: document.getElementById('picker'),
    numberOfMonths: 2,
    numberOfColumns: 1,
    inlineMode: true,
    // display the reset button
    useResetBtn: true,
    // call this function when the reset button is clicked
    resetBtnCallback() {
         console.log('ok')
    } 
 });
```

### CODE REVIEW

**Comment by kl3sk** [comment]
Nice new feature but please tell me where I'm wrong, https://jsfiddle.net/klesk/bLpae1jt/.
I can't make it work.

**Comment by EmilienLeroy** [comment]
@kl3sk 
I think the feature was not been upload on the last version.
I don't find the field `useResetField `into the cdn :
image

But in my dev build i found it :
image

**Comment by kl3sk** [comment]
That what is found too, but your feature seems to be in the last release 1.0.32 https://github.com/wakirin/Litepicker/commits/master

**Comment by EmilienLeroy** [comment]
I try with my own build and it work well
https://codepen.io/emilienleroy/pen/OJVdjvd

**Comment by wakirin** [comment]
Nice catch! Just now published v1.0.33

**Comment by kl3sk** [comment]
Great the button appears, but I experiment problems again. The date doesn't reset as they do from @EmilienLeroy  example:

https://jsfiddle.net/klesk/pk9eg0qm/

**Comment by EmilienLeroy** [comment]
@kl3sk 
Removes the `resetBtnCallBack` field from the option. Because this function override the default function when the reset btn is click.

If you want use a custom function and clear the selection, you can do this :
```js
var picker = new Litepicker({
    element: document.getElementById('litepicker'),
    numberOfMonths: 2,
    numberOfColumns: 1,
    inlineMode: true,
    singleMode: false,
    // display the reset button
    useResetBtn: true,
    resetBtnCallBack() {
      // Do somethibg
      picker.clearSelection()
    }
});
```

**Comment by kl3sk** [comment]
OK cool I didn't notice this obvious solution 😄

**Pull request merged**
