### PR TITLE
Ie11 support

### PR DESCRIPTION
**Pull request by cwrsimon**
Litepicker is a neat piece of software, thank you for that! My colleagues and I are considering using Litepicker in our project. However, IE11 support is still a requirement we cannot discuss away. If you are interested, feel free to accept this pull request. Unfortunately, some of the code changes are quite severe (e.g. DateTime class no longer extends Date), but they were definitely necessary.

### CODE REVIEW

**Comment by jevenson** [comment]
Thanks for this effort, my organization still requires IE11 support as well. Do you think it would be possible to make this library support IE11 without changing the code? I'm wondering if babel could be used in the webpack config to change any code automatically to support IE11.

**Comment by wakirin** [comment]
Thanks for the pull request. 

I tried to run in IE11:

Screen Shot 2020-04-06 at 20 30 12

> I'm wondering if babel could be used in the webpack config to change any code automatically to support IE11.

I tried with babel, but then the result file is too large.
If you find a good way for achieve IE support without much increasing file size, I will be glad to merge it.

**Comment by jevenson** [comment]
I was able to get the date picker to open up with these changes in IE, but its not opening in the correct position relative to the input its attached to. There also appear to be some minor css issues as well.

@cwrsimon make sure to run lint on these changes, there are a few violations I've seen

**Comment by jevenson** [comment]
I found another change that will be required in `methods.ts`

https://github.com/wakirin/Litepicker/blob/b1d591d52a3b7d830ff0ce467f05c3f1e77eef6e/src/methods.ts#L132

`scrollX` and `scrollY` are replaced with `pageXOffset` and `pageYOffset` in IE11

```
    scrollX = window.scrollX || window.pageXOffset;
    scrollY = window.scrollY || window.pageYOffset;
```

**Comment by cwrsimon** [comment]
@jevenson Thank you for the valuable feedback. I only tested with the HTML file included in the repository (./tests/index.html). I cannot confirm the eight column phenomenon:
grafik
However, the month / year label seems to be out of place.
@wakirin You will need to include the polyfill for CSS properties in your HTML (see ./tests/index.html).

I doubt that it is possible to have full browser support (including IE11) AND a small file size. But what do projects do? Wouldn't it be possible to offer two files, one for ES6 with a small file size (e.g. litepicker.es6.js) and on for ES5 (e.g. litepicker.es5.js)?

**Comment by wakirin** [comment]
> <script>window.MSInputMethodContext && document.documentMode && document.write('<script src="../dist/js//ie11CustomProperties.js"><\x2fscript>');</script>

@cwrsimon, the `dist` folder is not included in the repository, could you put this file in the `src` folder ?
I will add another task in the webpack for copy this file to the dist folder on prod/dev build.

> the file size of dist/js/main.js increases by approximately 3 KB

3KB is good, but does it included the polyfill (ie11CustomProperties.js) ?

**Comment by wakirin** [comment]
Very good, now everything is fine in IE11.
I guess it is better to create two different files (es6, es5) as you suggested in the previous comment:
> Wouldn't it be possible to offer two files, one for ES6 with a small file size (e.g. litepicker.es6.js) and on for ES5 (e.g. litepicker.es5.js)?

es5 will include polyfill, es6 will be without it.
Let me know what you are think about this ?
Thanks.

**Comment by jevenson** [comment]
@cwrsimon I'm wondering if the tests folder is the appropriate place to put that polyfills file. Since its a file that needs to be included in the website when supporting IE, I think it might be better suited in the src folder, perhaps in a polyfills subdirectory

Thoughts?

**Comment by cwrsimon** [comment]
Good question. Actually, I think I would leave it as it is right now and add the polyfill when required. The polyfill for the CSS properties is from this project: https://github.com/nuxodin/ie11CustomProperties
People who use Litepicker and know that they have IE11 users must be made aware of the fact that they need to add some CSS property polyfill from some source. You could also add ie11CustomProperties from a CDN, for instance:
https://www.jsdelivr.com/package/npm/ie11-custom-properties
Also, there are other polyfills around (e.g. https://github.com/jhildenbiddle/css-vars-ponyfill). Hence, I wouldn't bundle the polyfill, but leave it to the programmer who integrates Litepicker to integrate a polyfill when needed. Programmers who don't know that could be made aware of using documentation ;-)

**Comment by jevenson** [comment]
Okay gotcha, I understand. That makes sense.

**Comment by wakirin** [comment]
Thanks! I will publish a new version soon.

**Comment by jevenson** [comment]
A good optimization might be to add a linter to check future code changes for IE11 compatibility. This would help prevent breaking IE11 support down the line if its a goal to try and maintain it.

I found this one, which seems to check if any unsupported APIs are used.
https://github.com/jgardella/compat

**Pull request merged**
